"""Laptop-only RecoveryBox adapters."""

from .audio import (
    LaptopAudioError,
    MacOSAudioConfig,
    MacOSAudioPlayer,
    PlaybackCancelledError,
    PlaybackTicket,
)
from .microphone import (
    LaptopMicrophoneConfig,
    LaptopMicrophoneError,
    LaptopMicrophoneRecorder,
)
from .pose_model import (
    DEFAULT_POSE_MODEL_PATH,
    POSE_LANDMARKER_LITE_V1_SHA256,
    POSE_LANDMARKER_LITE_V1_SIZE_BYTES,
    POSE_LANDMARKER_LITE_V1_URL,
    PoseModelDownloadError,
    PoseModelError,
    PoseModelIntegrityError,
    PoseModelNotInstalledError,
    install_pose_model,
    validate_pose_model,
)
from .squat_launcher import (
    SQUAT_DEMO_INSTRUCTIONS,
    LaptopRuntimePinError,
    LaptopSquatDemo,
    SquatDemoCommand,
    SquatDemoConfig,
    SquatDemoDependencies,
    SquatDemoEndReason,
    SquatDemoResult,
    TerminalCommandSource,
    build_squat_demo,
    run_squat_demo,
    validate_laptop_runtime_pins,
)
from .squat_session import (
    DEFAULT_SINGLE_CAMERA_SQUAT_PLAN,
    SQUAT_EXERCISE_ID,
    SQUAT_REP_CUE_IDS,
    LaptopSquatSession,
    SquatAudioTurnResult,
    SquatSessionAnalysisResult,
    SquatSessionDispatchResult,
    build_single_camera_squat_plan,
    local_cue_request_for_squat_event,
    observation_from_squat_analysis,
)

__all__ = [
    "DEFAULT_POSE_MODEL_PATH",
    "DEFAULT_SINGLE_CAMERA_SQUAT_PLAN",
    "POSE_LANDMARKER_LITE_V1_SHA256",
    "POSE_LANDMARKER_LITE_V1_SIZE_BYTES",
    "POSE_LANDMARKER_LITE_V1_URL",
    "SQUAT_DEMO_INSTRUCTIONS",
    "SQUAT_EXERCISE_ID",
    "SQUAT_REP_CUE_IDS",
    "LaptopAudioError",
    "LaptopMicrophoneConfig",
    "LaptopMicrophoneError",
    "LaptopMicrophoneRecorder",
    "LaptopRuntimePinError",
    "LaptopSquatDemo",
    "LaptopSquatSession",
    "MacOSAudioConfig",
    "MacOSAudioPlayer",
    "PlaybackCancelledError",
    "PlaybackTicket",
    "PoseModelDownloadError",
    "PoseModelError",
    "PoseModelIntegrityError",
    "PoseModelNotInstalledError",
    "SquatAudioTurnResult",
    "SquatDemoCommand",
    "SquatDemoConfig",
    "SquatDemoDependencies",
    "SquatDemoEndReason",
    "SquatDemoResult",
    "SquatSessionAnalysisResult",
    "SquatSessionDispatchResult",
    "TerminalCommandSource",
    "build_single_camera_squat_plan",
    "build_squat_demo",
    "install_pose_model",
    "local_cue_request_for_squat_event",
    "observation_from_squat_analysis",
    "run_squat_demo",
    "validate_laptop_runtime_pins",
    "validate_pose_model",
]
