"""Clean protocol, transport, validation, and safety boundaries for Realtime."""

from recoverybox.session_end import RuntimeAbortReason

from .client import RealtimeClientResult, RealtimeSession, RejectedToolCall
from .cue_delivery import (
    DEFAULT_CUE_DELIVERY_CONFIG,
    CueDeliveryConfig,
    CueDeliveryError,
    CueDeliveryFailure,
    CueDeliveryFailureReason,
    CueDeliverySnapshot,
    CueEnqueueResult,
    CueQueueDisposition,
    PromptCueSession,
    RealtimeCueDelivery,
    ReleasedCueAudio,
)
from .device_adapter import (
    RealtimeConversationAdapter,
    RealtimeEventSink,
    RealtimeTurnPolicy,
    select_realtime_turn_policy,
)
from .prompts import (
    build_prompt_cue_response_instructions,
    build_realtime_session_instructions,
)
from .protocol import (
    PCM_CHANNELS,
    PCM_FORMAT,
    PCM_SAMPLE_RATE_HZ,
    PCM_SAMPLE_WIDTH_BYTES,
    REALTIME_MODEL,
    REALTIME_WEBSOCKET_URL,
    ParsedServerEvent,
    RealtimeProtocolError,
    ServerEventKind,
    build_assistant_item_truncate,
    build_audio_append,
    build_audio_clear,
    build_audio_commit,
    build_function_call_output,
    build_prompt_cue_response_create,
    build_response_cancel,
    build_response_create,
    build_session_update,
    parse_server_event,
)
from .safety import (
    AudioGateError,
    ConversationMode,
    ModelAudioGate,
    ModelAudioPolicy,
    ReleasedModelAudio,
    normalize_authorized_text,
)
from .session_control import (
    FINISH_SESSION_TOOL,
    FINISH_SESSION_TOOL_NAME,
    SESSION_CONTROL_TOOL_REGISTRY,
    SessionControlError,
    SessionEndController,
    SessionEndSignal,
    SessionEndSource,
    validate_finish_session_call,
)
from .tools import (
    FunctionTool,
    ToolRegistry,
    ToolValidationError,
    ValidatedToolCall,
    extract_validated_tool_calls,
)
from .transport import (
    BoundedOrderedTransport,
    MemoryTransport,
    RealtimeTransport,
    RealtimeTransportBackpressureError,
    RealtimeTransportUnavailableError,
    WebSocketJsonTransport,
)

__all__ = [
    "DEFAULT_CUE_DELIVERY_CONFIG",
    "FINISH_SESSION_TOOL",
    "FINISH_SESSION_TOOL_NAME",
    "PCM_CHANNELS",
    "PCM_FORMAT",
    "PCM_SAMPLE_RATE_HZ",
    "PCM_SAMPLE_WIDTH_BYTES",
    "REALTIME_MODEL",
    "REALTIME_WEBSOCKET_URL",
    "SESSION_CONTROL_TOOL_REGISTRY",
    "AudioGateError",
    "BoundedOrderedTransport",
    "ConversationMode",
    "CueDeliveryConfig",
    "CueDeliveryError",
    "CueDeliveryFailure",
    "CueDeliveryFailureReason",
    "CueDeliverySnapshot",
    "CueEnqueueResult",
    "CueQueueDisposition",
    "FunctionTool",
    "MemoryTransport",
    "ModelAudioGate",
    "ModelAudioPolicy",
    "ParsedServerEvent",
    "PromptCueSession",
    "RealtimeClientResult",
    "RealtimeConversationAdapter",
    "RealtimeCueDelivery",
    "RealtimeEventSink",
    "RealtimeProtocolError",
    "RealtimeSession",
    "RealtimeTransport",
    "RealtimeTransportBackpressureError",
    "RealtimeTransportUnavailableError",
    "RealtimeTurnPolicy",
    "RejectedToolCall",
    "ReleasedCueAudio",
    "ReleasedModelAudio",
    "RuntimeAbortReason",
    "ServerEventKind",
    "SessionControlError",
    "SessionEndController",
    "SessionEndSignal",
    "SessionEndSource",
    "ToolRegistry",
    "ToolValidationError",
    "ValidatedToolCall",
    "WebSocketJsonTransport",
    "build_assistant_item_truncate",
    "build_audio_append",
    "build_audio_clear",
    "build_audio_commit",
    "build_function_call_output",
    "build_prompt_cue_response_create",
    "build_prompt_cue_response_instructions",
    "build_realtime_session_instructions",
    "build_response_cancel",
    "build_response_create",
    "build_session_update",
    "extract_validated_tool_calls",
    "normalize_authorized_text",
    "parse_server_event",
    "select_realtime_turn_policy",
    "validate_finish_session_call",
]
